AWSTemplateFormatVersion: "2010-09-09"

Description: This template creates an autoscaling group with EC2 instances in a VPC with 2 public subnets. The instances have an apache web server installed.

# Parameters:
#   VpcId:
#     Type: 'AWS::EC2::VPC::Id'
#     Description: VpcId of your existing Virtual Private Cloud (VPC)
#     ConstraintDescription: must be the VPC Id of an existing Virtual Private Cloud.

#   LaunchTemplateVersionNumber:
#     Default: 1
#     Type: String

#   KeyName:
#     Description: The EC2 Key Pair to allow SSH access to the instances
#     Type: 'AWS::EC2::KeyPair::KeyName'
#     ConstraintDescription: must be the name of an existing EC2 KeyPair.

#   SSHLocation:
#     AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
#     ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
#     Default: 0.0.0.0/0
#     Description: The IP address range that can be used to access the web server using SSH.
#     MaxLength: '18'
#     MinLength: '9'
#     Type: String
Resources:
  LaunchTemplate:
    Type: 'AWS::EC2::LaunchTemplate'
    Properties:
      LaunchTemplateName: 'consul-cft'
      LaunchTemplateData:
        NetworkInterfaces:
          - DeviceIndex: 0
            AssociatePublicIpAddress: true
            Groups:
              - sg-IDS
            DeleteOnTermination: true
        Placement:
          Tenancy: default
        ImageId: <AMI ID>
        KeyName: <KEY PAIR NAME>
        InstanceType: t2.micro
        UserData:
          Fn::Base64:
             |
               #!/bin/bash -xe
                service consul stop
                cat > /etc/consul.d/consul.json <<EOF
                {
                    "bootstrap_expect": 5,
                    "raft_protocol": 3,
                    "client_addr": "0.0.0.0",
                    "datacenter": "us-east-1",
                    "data_dir": "/opt/consul",
                    "enable_script_checks": true,
                    "telemetry": {
                      "prometheus_retention_time": "1h"
                    },
                    "dns_config": {
                        "enable_truncate": true,
                        "only_passing": true
                    },
                    "enable_syslog": true,
                    "leave_on_terminate": true,
                    "log_level": "INFO",
                    "rejoin_after_leave": true,
                    "server": true,
                      "retry_join": ["provider=aws tag_key=Application tag_value=Consul"],
                    "ui": true,
                    "connect": {
                  "enabled": true
                        }
                }
                EOF
                rm -rf /opt/consul/checkpoint-signature
                rm -rf /opt/consul/node-id 
                rm -rf /opt/consul/raft/ 
                rm -rf /opt/consul/serf/

                service consul start

  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      MinSize: '5'
      MaxSize: '5'
      DesiredCapacity: '5'
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplate
        Version: !Ref LaunchTemplateVersionNumber
      VPCZoneIdentifier:
        - subnet-id1
        - subnet-id2